<a href="https://colab.research.google.com/github/SchunckCCS/Pandas_alura/blob/main/Exercicios_Pandas_Katas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercícios de Pandas

Use a célula abaixo para criar o DataFrame fornecido pelo ChatGPT.

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "Aluno": ["Ana", "Bruno", "Carlos", "Daniel", "Eduarda",
               "Fernanda", "Gabriel", "Helena", "Igor", "Julia"],

    "Curso": ["Python", "Python", "Java", "Python", "Java",
              "C++", "Python", "C++", "Java", "Python"],

    "Idade": [20, 22, 19, 25, 21, 24, 23, 20, 22, 21],

    "Nota": [8.5, 6.0, 9.2, 7.1, 8.8, 5.5, 9.7, 6.8, 7.9, 10.0]
})

In [ ]:
df

      Aluno   Curso  Idade  Nota
0       Ana  Python     20   8.5
1     Bruno  Python     22   6.0
2    Carlos    Java     19   9.2
3    Daniel  Python     25   7.1
4   Eduarda    Java     21   8.8
5  Fernanda     C++     24   5.5
6   Gabriel  Python     23   9.7
7    Helena     C++     20   6.8
8      Igor    Java     22   7.9
9     Julia  Python     21  10.0

## Exercício 1 — Explorando os dados

### Questão 1

Mostre as estatísticas da coluna `Nota`.

In [ ]:
df["Nota"].describe()

count    10.000000
mean      7.950000
std       1.552954
min       5.500000
25%       6.875000
50%       8.200000
75%       9.100000
max      10.000000
Name: Nota, dtype: float64

### Questão 2

Descubra quantos alunos existem em cada curso.

In [ ]:
df["Curso"].value_counts()

Curso
Python    5
Java      3
C++       2
Name: count, dtype: int64

### Questão 3

Ordene os alunos pela maior nota.

In [ ]:
df.sort_values(by='Nota', ascending=False)

      Aluno   Curso  Idade  Nota
9     Julia  Python     21  10.0
6   Gabriel  Python     23   9.7
2    Carlos    Java     19   9.2
4   Eduarda    Java     21   8.8
0       Ana  Python     20   8.5
8      Igor    Java     22   7.9
3    Daniel  Python     25   7.1
7    Helena     C++     20   6.8
1     Bruno  Python     22   6.0
5  Fernanda     C++     24   5.5

### Questão 4

Ordene os alunos pela menor idade.

In [ ]:
df.sort_values(by='Idade', ascending=True)

      Aluno   Curso  Idade  Nota
2    Carlos    Java     19   9.2
0       Ana  Python     20   8.5
7    Helena     C++     20   6.8
4   Eduarda    Java     21   8.8
9     Julia  Python     21  10.0
1     Bruno  Python     22   6.0
8      Igor    Java     22   7.9
6   Gabriel  Python     23   9.7
5  Fernanda     C++     24   5.5
3    Daniel  Python     25   7.1

### Questão 5

Descubra qual curso possui mais alunos.

In [ ]:
df['Curso'].value_counts().idxmax()

'Python'

## Exercício 2 — Filtros e seleção

### Questão 1

Mostre apenas os alunos com nota maior ou igual a 8.

In [ ]:
df.loc[df['Nota'] >= 8]

     Aluno   Curso  Idade  Nota
0      Ana  Python     20   8.5
2   Carlos    Java     19   9.2
4  Eduarda    Java     21   8.8
6  Gabriel  Python     23   9.7
9    Julia  Python     21  10.0

### Questão 2

Mostre apenas os alunos do curso de Python.

In [ ]:
df.loc[df['Curso'] == 'Python']

     Aluno   Curso  Idade  Nota
0      Ana  Python     20   8.5
1    Bruno  Python     22   6.0
3   Daniel  Python     25   7.1
6  Gabriel  Python     23   9.7
9    Julia  Python     21  10.0

### Questão 3

Mostre apenas os alunos de Java com nota maior que 8.

In [ ]:
df.loc[(df['Curso'] == 'Java') & (df['Nota'] >= 8)]

     Aluno Curso  Idade  Nota
2   Carlos  Java     19   9.2
4  Eduarda  Java     21   8.8

### Questão 4

Mostre apenas as colunas `Aluno` e `Nota` dos alunos maiores de 21 anos.

In [33]:
df.loc[df['Idade'] > 21, ['Aluno', 'Nota']]

      Aluno  Nota
1     Bruno   6.0
3    Daniel   7.1
5  Fernanda   5.5
6   Gabriel   9.7
8      Igor   7.9

### Questão 5

Mostre o nome do aluno que tirou nota 10.

In [34]:
df.loc[df['Nota'] == 10, ['Aluno']]

   Aluno
9  Julia

## Exercício 3 — Agrupando informações

### Questão 1

Qual é a média das notas por curso?

In [37]:
df.groupby('Curso')['Nota'].mean().round(2)

Curso
C++       6.15
Java      8.63
Python    8.26
Name: Nota, dtype: float64

### Questão 2

Qual é a idade média dos alunos de cada curso?

In [39]:
df.groupby('Curso')['Idade'].mean().round(2)

Curso
C++       22.00
Java      20.67
Python    22.20
Name: Idade, dtype: float64

### Questão 3

Quantos alunos existem em cada curso usando `groupby()`?

In [41]:
df.groupby('Curso')['Aluno'].count()

Curso
C++       2
Java      3
Python    5
Name: Aluno, dtype: int64

### Questão 4

Qual foi a maior nota de cada curso?

In [44]:
df.groupby('Curso')['Nota'].max()

Curso
C++        6.8
Java       9.2
Python    10.0
Name: Nota, dtype: float64

### Questão 5

Qual foi a menor nota de cada curso?

In [45]:
df.groupby('Curso')['Nota'].min()

Curso
C++       5.5
Java      7.9
Python    6.0
Name: Nota, dtype: float64